"""Shared KiCad syntax and geometry primitives."""

from .copper import (
    Bounds,
    Box,
    Capsule,
    Field,
    Obstacle,
    RoutingError,
    Track,
    route_edge,
    route_net,
    track_is_clear,
)
from .pcb import PcbBoard, PcbFootprint, PcbNet, PcbPad, inspect_pcb
from .sexp import (
    Node,
    Replacement,
    SexpError,
    Token,
    apply_replacements,
    block_end,
    blocks,
    child,
    children,
    head,
    number,
    parse,
    text,
    token,
    tokenize,
    walk,
)

__all__ = [
    "Bounds",
    "Box",
    "Capsule",
    "Field",
    "Node",
    "Obstacle",
    "PcbBoard",
    "PcbFootprint",
    "PcbNet",
    "PcbPad",
    "Replacement",
    "RoutingError",
    "SexpError",
    "Token",
    "Track",
    "apply_replacements",
    "block_end",
    "blocks",
    "child",
    "children",
    "head",
    "inspect_pcb",
    "number",
    "parse",
    "route_edge",
    "route_net",
    "text",
    "token",
    "tokenize",
    "track_is_clear",
    "walk",
]

__version__ = "0.3.0"
