"""Shared KiCad syntax and geometry primitives."""

from .autoroute import AutorouteResult, NetTask, autoroute
from .component import (
    ComponentFinding,
    ComponentManifestError,
    ComponentReport,
    pin_map_hash,
    sha256_file,
    validate_component_file,
    validate_component_manifest,
)
from .copper import (
    Bounds,
    Box,
    Capsule,
    Field,
    Obstacle,
    RoutingError,
    Track,
    route_edge,
    route_net,
    track_is_clear,
)
from .maze import BLOCKED, FREE, MazeRouter, MazeSegment, MazeVia
from .netlist import (
    NetlistComponent,
    NetlistError,
    NetlistNet,
    NetlistNode,
    NetlistPin,
    SchematicNetlist,
    parse_netlist_xml,
)
from .pcb import (
    PcbBoard,
    PcbFootprint,
    PcbGraphicLine,
    PcbNet,
    PcbPad,
    PcbTrack,
    PcbVia,
    inspect_footprint,
    inspect_pcb,
)
from .sexp import (
    Node,
    Replacement,
    SexpError,
    Token,
    apply_replacements,
    block_end,
    blocks,
    child,
    children,
    head,
    number,
    parse,
    text,
    token,
    tokenize,
    walk,
)

__all__ = [
    "Bounds",
    "BLOCKED",
    "AutorouteResult",
    "Box",
    "Capsule",
    "ComponentFinding",
    "ComponentManifestError",
    "ComponentReport",
    "Field",
    "FREE",
    "MazeRouter",
    "MazeSegment",
    "MazeVia",
    "Node",
    "NetlistComponent",
    "NetTask",
    "NetlistError",
    "NetlistNet",
    "NetlistNode",
    "NetlistPin",
    "Obstacle",
    "PcbBoard",
    "PcbFootprint",
    "PcbGraphicLine",
    "PcbNet",
    "PcbPad",
    "PcbTrack",
    "PcbVia",
    "Replacement",
    "RoutingError",
    "SexpError",
    "SchematicNetlist",
    "Token",
    "Track",
    "apply_replacements",
    "autoroute",
    "block_end",
    "blocks",
    "child",
    "children",
    "head",
    "inspect_pcb",
    "inspect_footprint",
    "number",
    "parse",
    "parse_netlist_xml",
    "pin_map_hash",
    "route_edge",
    "route_net",
    "sha256_file",
    "text",
    "token",
    "tokenize",
    "track_is_clear",
    "validate_component_file",
    "validate_component_manifest",
    "walk",
]

__version__ = "0.9.0"
